[package]
name = "dressme"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde_json = "1.0.128"
druid = "0.6"
druid-shell = "0.6"
dotenv = "0.15.0"
